apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - sh
        - -c
        - |-
          python manage.py migrate
                python manage.py runserver 0.0.0.0:8010
        env:
        - name: DB_HOST
          value: db
        - name: DB_NAME
          value: app
        - name: DB_PASSWORD
          value: "12345"
        - name: DB_USER
          value: postgres
        - name: GET_HOSTS_FROM
          value: dns
        image: up2_web
        imagePullPolicy: "Never"
        name: django-book-website
        ports:
        - containerPort: 8010
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}